import { describe, expect, test } from "bun:test";
import type { BatchExtractedFact, ExtractedFact } from "@grounded/db";
import {
  applyQuoteValidation,
  assessChunk,
  buildEmbeddingInput,
  compactText,
  decideFactType,
  duplicateTripleRate,
  EXTRACTION_SYSTEM_PROMPT,
  findRepeatedStrings,
  hashPage,
  packPages,
  parseFallbackOutput,
  quoteLengthBucket,
  splitBatch,
  summarizeQuoteLengths,
  validateBatchResult,
  validateQuote,
} from "./extractor";

describe("extractor pure layer unit tests", () => {
  const sampleFact: ExtractedFact = {
    confidence: 0.95,
    currency: "INR",
    entity: {
      context: "Delhivery reported fourth-quarter revenue of 2076 Cr.",
      name: "Delhivery",
      type: "organization",
    },
    factTypeDescription: "Total quarterly revenue generated by an organization",
    predicate: "quarterly_revenue",
    qualifiers: { quarter: "Q4 FY24" },
    rawValue: "INR 2,076 Cr",
    sourceQuote: "Revenue from operations grew to INR 2,076 Cr in Q4 FY24.",
    timeScope: "Q4 FY24",
    unit: "Cr",
    value: "20760000000",
  };

  const sourceText =
    "Delhivery announced financial results. Revenue from operations grew to INR 2,076 Cr in Q4 FY24. Adjusted EBITDA improved.";

  test("1. validateQuote handles exact, trim-padded, mismatch, and empty quote cases", () => {
    // Exact match
    expect(validateQuote(sampleFact, sourceText)).toBe(true);

    // Trim-padded match
    expect(
      validateQuote(
        {
          sourceQuote:
            "   Revenue from operations grew to INR 2,076 Cr in Q4 FY24.   ",
        },
        sourceText
      )
    ).toBe(true);

    // Substring match
    expect(
      validateQuote({ sourceQuote: "Revenue from operations grew" }, sourceText)
    ).toBe(true);

    // Mismatch
    expect(
      validateQuote({ sourceQuote: "Revenue plummeted to 100 Cr" }, sourceText)
    ).toBe(false);

    // Empty or whitespace quote
    expect(validateQuote({ sourceQuote: "" }, sourceText)).toBe(false);
    expect(validateQuote({ sourceQuote: "   " }, sourceText)).toBe(false);
  });

  test("2. applyQuoteValidation: mismatch halves confidence, tags quoteMismatch, sets sourceQuoteValid=false", () => {
    const mismatchedFact: ExtractedFact = {
      ...sampleFact,
      confidence: 0.8,
      sourceQuote: "Total loss was 500 Cr",
    };

    const result = applyQuoteValidation(mismatchedFact, sourceText, false);

    expect(result.sourceQuoteValid).toBe(false);
    expect(result.fact.confidence).toBe(0.4);
    expect(result.fact.qualifiers?.quoteMismatch).toBe(true);
    expect(result.fact.predicate).toBe(mismatchedFact.predicate);
  });

  test("3. applyQuoteValidation: vision-only path sets sourceQuoteValid=false and visionOnly:true", () => {
    const result = applyQuoteValidation(sampleFact, "", true);

    expect(result.sourceQuoteValid).toBe(false);
    expect(result.visionOnly).toBe(true);
    expect(result.fact.qualifiers?.visionOnly).toBe(true);
    expect(result.fact.confidence).toBe(sampleFact.confidence);
    expect(result.fact.sourceQuote).toBe(sampleFact.sourceQuote);
  });

  test("4. parseFallbackOutput: parses valid JSON, rejects garbage and schema violations", () => {
    // Valid JSON with extraction result
    const validJson = JSON.stringify({
      facts: [sampleFact],
    });
    const validResult = parseFallbackOutput(validJson);
    expect(validResult.ok).toBe(true);
    if (validResult.ok) {
      expect(validResult.facts.length).toBe(1);
      expect(validResult.facts[0].predicate).toBe("quarterly_revenue");
    }

    // Garbage / non-JSON string
    const garbageResult = parseFallbackOutput("Sorry, I cannot extract facts.");
    expect(garbageResult.ok).toBe(false);

    // Schema-violating JSON (missing required entity name)
    const invalidJson = JSON.stringify({
      facts: [
        {
          predicate: "annual_revenue",
          value: "100",
        },
      ],
    });
    const invalidResult = parseFallbackOutput(invalidJson);
    expect(invalidResult.ok).toBe(false);
  });

  test("5. decideFactType: 0.91 links, 0.42 mints, null mints (respects threshold override)", () => {
    expect(decideFactType(0.91, 0.85)).toBe("link");
    expect(decideFactType(0.42, 0.85)).toBe("mint");
    expect(decideFactType(null, 0.85)).toBe("mint");

    // Threshold override
    expect(decideFactType(0.8, 0.75)).toBe("link");
    expect(decideFactType(0.8, 0.85)).toBe("mint");
  });

  test("6. assessChunk: categorizes chunks accurately according to new rules", () => {
    // Empty chunk without runs
    expect(
      assessChunk({
        rawText: "   ",
        runs: [],
      })
    ).toBe("skip");

    // Standard narrative text chunk
    expect(
      assessChunk({
        isLowText: false,
        isTableHeavy: false,
        rawText: "Standard narrative text explaining business operations.",
        runs: [{ text: "Standard" }],
      })
    ).toBe("extract-text");

    // Table-heavy page -> extract-text-table (text first!)
    expect(
      assessChunk({
        isLowText: false,
        isTableHeavy: true,
        rawText: "Col 1 | Col 2\n100 | 200",
        runs: [{ text: "100" }],
      })
    ).toBe("extract-text-table");

    // Scanned / low-text chunk with vision enabled -> extract-vision
    expect(
      assessChunk(
        {
          isLowText: true,
          rawText: "Scanned text <100 chars",
        },
        true
      )
    ).toBe("extract-vision");

    // Scanned / low-text chunk with vision disabled -> defer-vision-disabled
    expect(
      assessChunk(
        {
          isLowText: true,
          rawText: "Scanned text <100 chars",
        },
        false
      )
    ).toBe("defer-vision-disabled");
  });

  test("7. buildEmbeddingInput produces exact expected inline task prefix format", () => {
    const input = buildEmbeddingInput(sampleFact);
    expect(input).toBe("fact: Delhivery quarterly_revenue 20760000000");
  });

  test("8. EXTRACTION_SYSTEM_PROMPT contains all required rules (grounding + selectivity)", () => {
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("Rules:");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("explicitly stated");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("verbatim substring");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("snake_case");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("factTypeDescription");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("confidence below 0.7");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain('{"facts": []}');
    // Selectivity rules (conservative): minimal-span quotes, one fact per
    // (metric, scope, document), fragment skipping, both fact kinds covered.
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("minimal span");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain(
      "One fact per (metric, scope, document)"
    );
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("always keep both");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain(
      "Skip fragments and restatements"
    );
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("semantic facts");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("emit the fact once");
  });

  test("9. packPages groups pages preserving order and handles oversize loners and small docs", () => {
    // Small doc: 3 pages collapse to 1 batch
    const smallDoc = [
      { pageNumber: 1, text: "Page 1 short", tokenEstimate: 500 },
      { pageNumber: 2, text: "Page 2 short", tokenEstimate: 500 },
      { pageNumber: 3, text: "Page 3 short", tokenEstimate: 500 },
    ];
    const smallBatches = packPages(smallDoc, 42_000);
    expect(smallBatches.length).toBe(1);
    expect(smallBatches[0].length).toBe(3);

    // Oversize loner gets its own batch
    const withOversize = [
      { pageNumber: 1, text: "Page 1", tokenEstimate: 500 },
      { pageNumber: 2, text: "Oversize Page", tokenEstimate: 30_000 },
      { pageNumber: 3, text: "Page 3", tokenEstimate: 500 },
    ];
    const batches = packPages(withOversize, 40_000);
    expect(batches.length).toBe(3);
    expect(batches[0][0].pageNumber).toBe(1);
    expect(batches[1][0].pageNumber).toBe(2);
    expect(batches[2][0].pageNumber).toBe(3);
  });

  test("10. compactText & findRepeatedStrings strips recurring chrome across pages", () => {
    const pages = [
      { text: "Acme Corp Annual Report 2024\nRevenue was 100M\nConfidential" },
      { text: "Acme Corp Annual Report 2024\nProfit was 20M\nConfidential" },
      { text: "Acme Corp Annual Report 2024\nExpenses were 80M\nConfidential" },
    ];

    const repeated = findRepeatedStrings(pages);
    expect(repeated).toContain("Acme Corp Annual Report 2024");
    expect(repeated).toContain("Confidential");

    const compacted = compactText(pages[0].text, repeated);
    expect(compacted).toBe("Revenue was 100M");
  });

  test("11. hashPage generates deterministic 16-hex hash", () => {
    const hash1 = hashPage("Same content");
    const hash2 = hashPage("Same content");
    const hash3 = hashPage("Different content");

    expect(hash1).toBe(hash2);
    expect(hash1.length).toBe(16);
    expect(hash1).not.toBe(hash3);
  });

  test("12. validateBatchResult drops facts with invented page numbers", () => {
    const batchFacts: BatchExtractedFact[] = [
      { ...sampleFact, pageNumber: 1 },
      { ...sampleFact, pageNumber: 2 },
      { ...sampleFact, pageNumber: 99 }, // Invented page number outside batch
    ];

    const allowed = new Set([1, 2]);
    const { validFacts, droppedCount } = validateBatchResult(
      batchFacts,
      allowed
    );

    expect(validFacts.length).toBe(2);
    expect(droppedCount).toBe(1);
    expect(validFacts.map((f) => f.pageNumber)).toEqual([1, 2]);
  });

  test("13. splitBatch splits batch in half", () => {
    const items = [1, 2, 3, 4, 5];
    const [left, right] = splitBatch(items);

    expect(left).toEqual([1, 2, 3]);
    expect(right).toEqual([4, 5]);

    const single = [1];
    const [singleLeft, singleRight] = splitBatch(single);
    expect(singleLeft).toEqual([1]);
    expect(singleRight).toEqual([]);
  });

  test("14. quoteLengthBucket + summarizeQuoteLengths bucket observed lengths (never enforced)", () => {
    expect(quoteLengthBucket(50)).toBe("0-100");
    expect(quoteLengthBucket(100)).toBe("0-100");
    expect(quoteLengthBucket(400)).toBe("101-400");
    expect(quoteLengthBucket(1000)).toBe("401-1000");
    expect(quoteLengthBucket(1001)).toBe("1000+");

    const summary = summarizeQuoteLengths([
      "short quote",
      "Revenue grew.",
      "x".repeat(500),
      "y".repeat(2000),
    ]);
    expect(summary).toEqual({
      "0-100": 2,
      "101-400": 0,
      "401-1000": 1,
      "1000+": 1,
    });
    expect(summarizeQuoteLengths([])).toEqual({
      "0-100": 0,
      "101-400": 0,
      "401-1000": 0,
      "1000+": 0,
    });
  });

  test("15. duplicateTripleRate scores over-extraction (selectivity scoreboard)", () => {
    const facts = [
      { predicate: "total_revenue", timeScope: "FY2023", value: "4200M" },
      { predicate: "total_revenue", timeScope: "FY2023", value: "4200M" },
      { predicate: "total_revenue", timeScope: "FY2024", value: "4800M" },
      { predicate: "net_income", timeScope: null, value: "890M" },
    ];
    const { duplicates, rate, total } = duplicateTripleRate(facts);
    expect(total).toBe(4);
    expect(duplicates).toBe(1);
    expect(rate).toBe(0.25);

    // Same metric, different scope is NOT a duplicate (reconciled-case material).
    const scoped = duplicateTripleRate([
      { predicate: "total_revenue", timeScope: "FY2022", value: "3750M" },
      { predicate: "total_revenue", timeScope: "FY2023", value: "4200M" },
    ]);
    expect(scoped.duplicates).toBe(0);
    expect(scoped.rate).toBe(0);

    expect(duplicateTripleRate([])).toEqual({
      duplicates: 0,
      rate: 0,
      total: 0,
    });
  });
});
