import { describe, expect, test } from "bun:test";
import type { ExtractedFact } from "@grounded/db";
import {
  applyQuoteValidation,
  assessChunk,
  buildEmbeddingInput,
  decideFactType,
  EXTRACTION_SYSTEM_PROMPT,
  parseFallbackOutput,
  validateQuote,
} from "./extractor";

describe("extractor pure layer unit tests", () => {
  const sampleFact: ExtractedFact = {
    confidence: 0.95,
    currency: "INR",
    entity: {
      context: "Delhivery reported fourth-quarter revenue of 2076 Cr.",
      name: "Delhivery",
      type: "organization",
    },
    factTypeDescription: "Total quarterly revenue generated by an organization",
    predicate: "quarterly_revenue",
    qualifiers: [{ key: "quarter", value: "Q4 FY24" }],
    rawValue: "INR 2,076 Cr",
    sourceQuote: "Revenue from operations grew to INR 2,076 Cr in Q4 FY24.",
    timeScope: "Q4 FY24",
    unit: "Cr",
    value: "20760000000",
  };

  const sourceText =
    "Delhivery announced financial results. Revenue from operations grew to INR 2,076 Cr in Q4 FY24. Adjusted EBITDA improved.";

  test("1. validateQuote handles exact, trim-padded, mismatch, and empty quote cases", () => {
    // Exact match
    expect(validateQuote(sampleFact, sourceText)).toBe(true);

    // Trim-padded match
    expect(
      validateQuote(
        {
          sourceQuote:
            "   Revenue from operations grew to INR 2,076 Cr in Q4 FY24.   ",
        },
        sourceText
      )
    ).toBe(true);

    // Substring match
    expect(
      validateQuote({ sourceQuote: "Revenue from operations grew" }, sourceText)
    ).toBe(true);

    // Mismatch
    expect(
      validateQuote({ sourceQuote: "Revenue plummeted to 100 Cr" }, sourceText)
    ).toBe(false);

    // Empty or whitespace quote
    expect(validateQuote({ sourceQuote: "" }, sourceText)).toBe(false);
    expect(validateQuote({ sourceQuote: "   " }, sourceText)).toBe(false);
  });

  test("2. applyQuoteValidation: mismatch halves confidence, tags quoteMismatch, sets sourceQuoteValid=false", () => {
    const mismatchedFact: ExtractedFact = {
      ...sampleFact,
      confidence: 0.8,
      sourceQuote: "Total loss was 500 Cr",
    };

    const result = applyQuoteValidation(mismatchedFact, sourceText, false);

    expect(result.sourceQuoteValid).toBe(false);
    expect(result.fact.confidence).toBe(0.4);
    expect(result.fact.qualifiers).toContainEqual({
      key: "quoteMismatch",
      value: "true",
    });
    expect(result.fact.predicate).toBe(mismatchedFact.predicate);
  });

  test("3. applyQuoteValidation: vision-only path skips string check, sets visionOnly:true, keeps fact", () => {
    const result = applyQuoteValidation(sampleFact, "", true);

    expect(result.sourceQuoteValid).toBe(true);
    expect(result.visionOnly).toBe(true);
    expect(result.fact.qualifiers).toContainEqual({
      key: "visionOnly",
      value: "true",
    });
    expect(result.fact.confidence).toBe(sampleFact.confidence); // Confidence not penalized on vision path
    expect(result.fact.sourceQuote).toBe(sampleFact.sourceQuote);
  });

  test("4. parseFallbackOutput: parses valid JSON, rejects garbage and schema violations", () => {
    // Valid JSON with extraction result
    const validJson = JSON.stringify({
      facts: [sampleFact],
    });
    const validResult = parseFallbackOutput(validJson);
    expect(validResult.ok).toBe(true);
    if (validResult.ok) {
      expect(validResult.facts.length).toBe(1);
      expect(validResult.facts[0].predicate).toBe("quarterly_revenue");
    }

    // Garbage / non-JSON string
    const garbageResult = parseFallbackOutput("Sorry, I cannot extract facts.");
    expect(garbageResult.ok).toBe(false);

    // Schema-violating JSON (missing required entity name)
    const invalidJson = JSON.stringify({
      facts: [
        {
          predicate: "annual_revenue",
          value: "100",
        },
      ],
    });
    const invalidResult = parseFallbackOutput(invalidJson);
    expect(invalidResult.ok).toBe(false);
  });

  test("5. decideFactType: 0.91 links, 0.42 mints, null mints (respects threshold override)", () => {
    expect(decideFactType(0.91, 0.85)).toBe("link");
    expect(decideFactType(0.42, 0.85)).toBe("mint");
    expect(decideFactType(null, 0.85)).toBe("mint");

    // Threshold override
    expect(decideFactType(0.8, 0.75)).toBe("link");
    expect(decideFactType(0.8, 0.85)).toBe("mint");
  });

  test("6. assessChunk: categorizes chunks accurately according to rules", () => {
    const originalVision = process.env.VISION_ENABLED;

    try {
      // Empty chunk without runs
      expect(
        assessChunk({
          rawText: "   ",
          runs: [],
        })
      ).toBe("skip-empty");

      // Standard dense narrative text chunk
      expect(
        assessChunk({
          isLowText: false,
          isTableHeavy: false,
          needsVision: false,
          rawText: "Standard narrative text explaining business operations.",
          runs: [{ text: "Standard" }],
        })
      ).toBe("extract-text");

      // Vision needed with VISION_ENABLED='1'
      process.env.VISION_ENABLED = "1";
      expect(
        assessChunk({
          isTableHeavy: true,
          needsVision: true,
          rawText: "Table content",
          runs: [{ text: "123" }],
        })
      ).toBe("extract-vision");

      // Vision needed with VISION_ENABLED='0' (defer)
      process.env.VISION_ENABLED = "0";
      expect(
        assessChunk({
          isTableHeavy: true,
          needsVision: true,
          rawText: "Table content",
          runs: [{ text: "123" }],
        })
      ).toBe("defer-vision-disabled");
    } finally {
      if (originalVision === undefined) {
        delete process.env.VISION_ENABLED;
      } else {
        process.env.VISION_ENABLED = originalVision;
      }
    }
  });

  test("7. buildEmbeddingInput produces exact expected inline task prefix format", () => {
    const input = buildEmbeddingInput(sampleFact);
    expect(input).toBe("fact: Delhivery quarterly_revenue 20760000000");
  });

  test("8. EXTRACTION_SYSTEM_PROMPT contains all 6 required rules", () => {
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("Rules:");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("explicitly stated");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("verbatim substring");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("snake_case");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("factTypeDescription");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain("confidence below 0.7");
    expect(EXTRACTION_SYSTEM_PROMPT).toContain('{"facts": []}');
  });
});
